name: Seamus Deivert Sound Design
favicon: null
layout_spectrum: 0.3083354302216321
typography_spectrum: 0.2527802239637822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0819202724378556
  lightness: 0.7969304705038667
  saturation: 0.15617932355962694
  rhythmicContrast: 0.9843361130915582
purpose: []
